In [8]:
import pandas as pd
df = pd.read_csv("diabetes.csv")
df.head(8)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148.0,72.0,35.0,NaN,33.6,0.627,50,1
1,1,85.0,66.0,29.0,NaN,26.6,0.351,31,0
2,8,183.0,64.0,NaN,NaN,23.3,0.672,32,1
3,1,89.0,66.0,23.0,94.0,28.1,0.167,21,0
4,0,137.0,40.0,35.0,168.0,43.1,2.288,33,1
5,5,116.0,74.0,NaN,NaN,25.6,0.201,30,0
6,3,78.0,50.0,32.0,88.0,31.0,0.248,26,1
7,10,115.0,NaN,NaN,NaN,35.3,0.134,29,0

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   763 non-null    float64
 2   BloodPressure             733 non-null    float64
 3   SkinThickness             541 non-null    float64
 4   Insulin                   394 non-null    float64
 5   BMI                       757 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(6), int64(3)
memory usage: 54.1 KB

In [12]:
df.shape

(768, 9)

In [13]:
df.isna().sum()

Pregnancies                   0
Glucose                       5
BloodPressure                35
SkinThickness               227
Insulin                     374
BMI                          11
DiabetesPedigreeFunction      0
Age                           0
Outcome                       0
dtype: int64

In [19]:
to_fill = ("Glucose", "BloodPressure", "SkinThickness", "Insulin", "BMI")
for col in to_fill:
    df[col] = df[col].fillna(df[col].mean())
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,121.686763,72.405184,29.15342,155.548223,32.457464,0.627,50,1
1,1,121.686763,72.405184,29.15342,155.548223,32.457464,0.351,31,0
2,8,121.686763,72.405184,29.15342,155.548223,32.457464,0.672,32,1
3,1,121.686763,72.405184,29.15342,155.548223,32.457464,0.167,21,0
4,0,121.686763,72.405184,29.15342,155.548223,32.457464,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,121.686763,72.405184,29.15342,155.548223,32.457464,0.171,63,0
764,2,121.686763,72.405184,29.15342,155.548223,32.457464,0.340,27,0
765,5,121.686763,72.405184,29.15342,155.548223,32.457464,0.245,30,0
766,1,121.686763,72.405184,29.15342,155.548223,32.457464,0.349,47,1
767,1,121.686763,72.405184,29.15342,155.548223,32.457464,0.315,23,0